# Generated by Django 4.0.6 on 2022-07-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
