# Generated by Django 4.0.6 on 2022-07-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='order_status',
            field=models.CharField(max_length=50),
        ),
    ]
